#!/bin/sh

export WEBAPI_URL=https://${HOST}${NB_PREFIX}/WebAPI/
echo $WEBAPI_URL
export DATASOURCE_URL=jdbc:postgresql://${DATASOURCE_CONNECTION_HOST}:5432/${DATASOURCE_USERNAME}
echo $DATASOURCE_URL
export FLYWAY_DATASOURCE_URL=jdbc:postgresql://${FLYWAY_DATASOURCE_CONNECTION_HOST}:5432/${FLYWAY_DATASOURCE_USERNAME}
echo $FLYWAY_DATASOURCE_URL
./docker-entrypoint.sh nginx -g 'daemon off;'
