apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ohdsi-inap.fullname" . }}-secrets
data:
  {{- if and .Values.postgres.database .Values.postgres.host .Values.postgres.port }}
  datasource_url: {{ printf "jdbc:postgresql://%s:%s/%s" .Values.postgres.host .Values.postgres.port .Values.postgres.database | b64enc }}
  {{- end }}
  {{- if .Values.postgres.password }}
  datasource_password: {{ .Values.postgres.password | b64enc }}
  {{- end }}
  {{- if .Values.postgres.user }}
  datasource_username: {{ .Values.postgres.user | b64enc }}
  {{- end }}
